---
- hosts: all
  become: true
  roles:
    - geerlingguy.docker
  tasks:
  - name: Clone github repository
    git:
      repo: https://github.com/likheketo/walkietalkie
      dest: /home/ubuntu/walkietalkie
      clone: yes
      update: yes
  - name: Start backend server
    shell:
      cmd: "docker-compose up -d"
      chdir: /home/ubuntu/walkietalkie/backend
